### ISSUE TITLE
Question: Why doesn't the updateFunction await?

### ISSUE THREAD

**Issue by Yokoi-K** [yeniel/version_migration#5]
## description
↓I'd like to know why updateFuntion in applicationUpdate doesn't do await.
https://github.com/yeniel/version_migration/blob/master/lib/version_migration.dart#L34

In my opinion.
Since the migrationFunction in migrateToVersion is await, 
I think applicationUpdate should be await as well.
https://github.com/yeniel/version_migration/blob/master/lib/version_migration.dart#L20

Because I need to use await in updateFunction.🙏🙇‍♂️

**Comment by yeniel** [comment]
Done in the last update! 🚀
Thanks for you comment! 🙂 👍
