### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by TheManuz** [yeniel/version_migration#6]
As I'm writing, `version_migration` has the following dependencies that can be updated:

- package_info_plus
    - ^3.0.2 => 4.1.0
- shared_preferences
    - ^2.0.15 => 2.2.1
- platform
    - ^3.1.0 => 3.1.2
- file
    - ^6.1.4 => 7.0.0

I cannot update `package_info_plus` because of this.

**Comment by yeniel** [comment]
Done in the last update! 🚀 
Thanks for you comment! 🙂 👍

**Comment by TheManuz** [comment]
Thank you very much for your update!
